addpath(genpath('/home/lyfang/Lydia_Toolbox/PALM'));

palm( ...
  '-i','lDLPFC_FC_all.dscalar.nii', ...
  '-d','design.mat', ...
  '-t','design.con', ...
  '-n','5000', ...
  '-fdr', ...
  '-corrcon', ...
  '-o','lDLPFC_QIDS' ...
);


exit;
